-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES*B.PRICE) as TOTAL_SALES
FROM BOOK_SALES A
JOIN BOOK B
ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR C
ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE A.SALES_DATE LIKE '2022-01%'
GROUP BY C.AUTHOR_ID,C.AUTHOR_NAME,B.CATEGORY
ORDER BY 1, 3 DESC;