-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT*PRICE) AS SALES
FROM OFFLINE_SALE A
JOIN PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
HAVING SUM(SALES_AMOUNT*PRICE)
ORDER BY 2 DESC,1;