SELECT HISTORY_ID,
       ROUND(DAILY_FEE * PERIOD * (1-DISCOUNT_RATE)) AS FEE
FROM
(SELECT HISTORY_ID,
           DAILY_FEE,
           DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
           CASE 
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN 0
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN 0.05
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN 0.08
               ELSE 0.15
           END AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    JOIN CAR_RENTAL_COMPANY_CAR A
        ON B.CAR_ID = A.CAR_ID
            AND CAR_TYPE = '트럭') SUB
ORDER BY FEE DESC, HISTORY_ID DESC