-- 코드를 작성해주세요
SELECT A.EMP_NO, A.EMP_NAME, 
    CASE
    WHEN AVG(B.SCORE) >= 96 THEN 'S'
    WHEN AVG(B.SCORE) >= 90 AND AVG(B.SCORE) < 96 THEN 'A'
    WHEN AVG(B.SCORE) >= 80 AND AVG(B.SCORE) < 90 THEN 'B'
    ELSE 'C'
    END AS GRADE,
    CASE
    WHEN AVG(B.SCORE) >= 96 THEN 0.2 * A.SAL
    WHEN AVG(B.SCORE) >= 90 AND AVG(B.SCORE) < 96 THEN 0.15 * A.SAL
    WHEN AVG(B.SCORE) >= 80 AND AVG(B.SCORE) < 90 THEN 0.1 * A.SAL
    ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES A
JOIN HR_GRADE B
ON A.EMP_NO = B.EMP_NO
WHERE B.YEAR = 2022
GROUP BY A.EMP_NO, A.EMP_NAME, A.SAL
ORDER BY A.EMP_NO;